language:android

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.0

    # The SDK version used to compile your project
    - android-26
